version: '{build}'
image: Visual Studio 2017

environment:
  BOOST_ROOT: C:\Libraries\boost_1_67_0
  OPENSSL_ROOT_DIR: c:\beam-libs\openssl
  BUILD_SERVER:
    secure: 5oPcbgETrXo4nmgoqILqgzdjyghCp4tEsBR4gzpEall4E9Vy77ArnCHSRjtLIEai  
  BUILD_CONFIG: RelWithDebInfo

cache:
  - c:\tools\vcpkg\installed\

 
before_build:
  - cmd: git submodule update --init --recursive
  - cmd: git apply 3rdparty/protobuf-patch.diff
  - cmd: git clone --depth=1 https://github.com/BeamMW/libs.git c:/beam-libs
  - cmd: cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=%BUILD_CONFIG% -DBEAM_LINK_TYPE=Static -DBRANCH_NAME=%APPVEYOR_REPO_BRANCH% -DBEAM_BUILD_JNI=On -DBEAM_HW_WALLET=Off .

test_script:
  - cmd: ctest -C %BUILD_CONFIG% --verbose

build_script:
  - cmake --build . --parallel --config %BUILD_CONFIG%

after_build:
- ps: $env:DATE=[TimeZoneInfo]::ConvertTimeBySystemTimeZoneId([DateTime]::UtcNow, "Belarus Standard Time").ToString('yyyy.MM.dd')
- ps: $env:TIME=[TimeZoneInfo]::ConvertTimeBySystemTimeZoneId([DateTime]::UtcNow, "Belarus Standard Time").ToString('HH:mm:ss')
- ps: $env:BEAM_TARGET_SUFFIX='-testnet'
- ps: $env:BEAM_DISPLAY_SUFFIX='Testnet'
- ps: $env:BEAM_DISPLAY_SUFFIX2='-Testnet'
- ps: $env:BEAM_DISPLAY_SUFFIX3=' Testnet'
- cmd: >-
    set /p BEAM_VERSION=<beam_version.gen

    echo BEAM_VERSION = %BEAM_VERSION%

    del beam_version.gen
    
    7z a c:/projects/beam/beam/%BUILD_CONFIG%/beam-node%BEAM_TARGET_SUFFIX%-%BEAM_VERSION%.zip c:/projects/beam/beam/%BUILD_CONFIG%/beam-node%BEAM_TARGET_SUFFIX%.exe c:/projects/beam/beam/beam-node.cfg
    
    7z a c:/projects/beam/beam/%BUILD_CONFIG%/beam-wallet-cli%BEAM_TARGET_SUFFIX%-%BEAM_VERSION%.zip c:/projects/beam/wallet/cli/%BUILD_CONFIG%/beam-wallet%BEAM_TARGET_SUFFIX%.exe c:/projects/beam/wallet/cli/beam-wallet.cfg
    
    7z a c:/projects/beam/beam/%BUILD_CONFIG%/wallet-api%BEAM_TARGET_SUFFIX%-%BEAM_VERSION%.zip c:/projects/beam/wallet/api/%BUILD_CONFIG%/wallet-api%BEAM_TARGET_SUFFIX%.exe c:/projects/beam/wallet/api/wallet-api.cfg

    7z a c:/projects/beam/beam/%BUILD_CONFIG%/explorer-node%BEAM_TARGET_SUFFIX%-%BEAM_VERSION%.zip c:/projects/beam/explorer/%BUILD_CONFIG%/explorer-node%BEAM_TARGET_SUFFIX%.exe c:/projects/beam/explorer/explorer-node.cfg

    7z a c:/projects/beam/beam/%BUILD_CONFIG%/broadcaster%BEAM_TARGET_SUFFIX%-%BEAM_VERSION%.zip c:/projects/beam/wallet/broadcaster/%BUILD_CONFIG%/broadcaster%BEAM_TARGET_SUFFIX%.exe
        
    mkdir pdb
    
    7z a c:/projects/beam/beam/beam-pdb%BEAM_TARGET_SUFFIX%-%BEAM_VERSION%.zip "c:/projects/beam/beam/%BUILD_CONFIG%/beam-node%BEAM_TARGET_SUFFIX%.pdb" "c:/projects/beam/wallet/cli/%BUILD_CONFIG%/beam-wallet%BEAM_TARGET_SUFFIX%.pdb"

    copy c:\projects\beam\beam\%BUILD_CONFIG%\beam-node%BEAM_TARGET_SUFFIX%-%BEAM_VERSION%.zip c:\projects\beam\beam-node%BEAM_TARGET_SUFFIX%-%BEAM_VERSION%.zip

    copy c:\projects\beam\beam\%BUILD_CONFIG%\beam-wallet-cli%BEAM_TARGET_SUFFIX%-%BEAM_VERSION%.zip c:\projects\beam\beam-wallet-cli%BEAM_TARGET_SUFFIX%-%BEAM_VERSION%.zip

    copy c:\projects\beam\beam\%BUILD_CONFIG%\wallet-api%BEAM_TARGET_SUFFIX%-%BEAM_VERSION%.zip c:\projects\beam\wallet-api%BEAM_TARGET_SUFFIX%-%BEAM_VERSION%.zip

    copy c:\projects\beam\beam\%BUILD_CONFIG%\explorer-node%BEAM_TARGET_SUFFIX%-%BEAM_VERSION%.zip c:\projects\beam\explorer-node%BEAM_TARGET_SUFFIX%-%BEAM_VERSION%.zip

    copy c:\projects\beam\beam\%BUILD_CONFIG%\broadcaster%BEAM_TARGET_SUFFIX%-%BEAM_VERSION%.zip c:\projects\beam\broadcaster%BEAM_TARGET_SUFFIX%-%BEAM_VERSION%.zip

    copy c:\projects\beam\beam\beam-pdb%BEAM_TARGET_SUFFIX%-%BEAM_VERSION%.zip c:\projects\beam\pdb\beam-pdb%BEAM_TARGET_SUFFIX%-%BEAM_VERSION%.zip

on_success:
- ps: $env:DATE=[TimeZoneInfo]::ConvertTimeBySystemTimeZoneId([DateTime]::UtcNow, "Belarus Standard Time").ToString('yyyy.MM.dd')
- ps: $env:TIME=[TimeZoneInfo]::ConvertTimeBySystemTimeZoneId([DateTime]::UtcNow, "Belarus Standard Time").ToString('HH:mm:ss')
- cmd: >-
    set BUILDS_SERVER_PATH=%BUILD_SERVER%/files/%APPVEYOR_REPO_BRANCH%/%DATE%/Release/win
              
    curl --retry 3 --ftp-create-dirs -T "c:/projects/beam/beam/%BUILD_CONFIG%/beam-node%BEAM_TARGET_SUFFIX%-%BEAM_VERSION%.zip" "%BUILDS_SERVER_PATH%/beam-node%BEAM_TARGET_SUFFIX%-%BEAM_VERSION%.zip"

    curl --retry 3 --ftp-create-dirs -T "c:/projects/beam/beam/%BUILD_CONFIG%/beam-wallet-cli%BEAM_TARGET_SUFFIX%-%BEAM_VERSION%.zip" "%BUILDS_SERVER_PATH%/beam-wallet-cli%BEAM_TARGET_SUFFIX%-%BEAM_VERSION%.zip"

    curl --retry 3 --ftp-create-dirs -T "c:/projects/beam/beam/%BUILD_CONFIG%/wallet-api%BEAM_TARGET_SUFFIX%-%BEAM_VERSION%.zip" "%BUILDS_SERVER_PATH%/wallet-api%BEAM_TARGET_SUFFIX%-%BEAM_VERSION%.zip"

    curl --retry 3 --ftp-create-dirs -T "c:/projects/beam/beam/%BUILD_CONFIG%/explorer-node%BEAM_TARGET_SUFFIX%-%BEAM_VERSION%.zip" "%BUILDS_SERVER_PATH%/explorer-node%BEAM_TARGET_SUFFIX%-%BEAM_VERSION%.zip"

    curl --retry 3 --ftp-create-dirs -T "c:/projects/beam/beam/%BUILD_CONFIG%/broadcaster%BEAM_TARGET_SUFFIX%-%BEAM_VERSION%.zip" "%BUILDS_SERVER_PATH%/broadcaster%BEAM_TARGET_SUFFIX%-%BEAM_VERSION%.zip"

    curl --retry 3 --ftp-create-dirs -T "c:/projects/beam/beam/beam-pdb%BEAM_TARGET_SUFFIX%-%BEAM_VERSION%.zip" "%BUILDS_SERVER_PATH%/pdb/beam-pdb%BEAM_TARGET_SUFFIX%-%BEAM_VERSION%.zip"

artifacts:
  - path: beam-node%BEAM_TARGET_SUFFIX%-%BEAM_VERSION%.zip
    name: BeamNode

  - path: beam-wallet-cli%BEAM_TARGET_SUFFIX%-%BEAM_VERSION%.zip
    name: BeamWalletCli

  - path: wallet-api%BEAM_TARGET_SUFFIX%-%BEAM_VERSION%.zip
    name: BeamWalletApi

  # - path: wallet-service%BEAM_TARGET_SUFFIX%-%BEAM_VERSION%.zip
  #  name: BeamWalletService

  # - path: sbbs-monitor%BEAM_TARGET_SUFFIX%-%BEAM_VERSION%.zip
  #  name: BeamSbbsMonitor

  - path: explorer-node%BEAM_TARGET_SUFFIX%-%BEAM_VERSION%.zip
    name: BeamNodeExplorer

  - path: broadcaster%BEAM_TARGET_SUFFIX%-%BEAM_VERSION%.zip
    name: BeamBroadcaster

  - path: pdb/beam-pdb%BEAM_TARGET_SUFFIX%-%BEAM_VERSION%.zip
    name: BeamPdb

deploy:
  provider: S3
  access_key_id:
    secure: vku9qEnfo8NirxsplNRBBezWqJa1sV5eSfpt2syfwwk=
  secret_access_key:
    secure: sBTxw2gzbkQrPyMDF5OihFJ+s96yDgNgqbF1/MNmWpYMKrZwkOzIeExfW4Cp3F8B
  bucket: builds.beam.mw
  region: us-west-2
  unzip: false
  set_public: true
  folder: "%APPVEYOR_REPO_BRANCH%/%DATE%/Release/win/"
  artifact: BeamPdb, BeamWalletApi, BeamWalletService, BeamSbbsMonitor, BeamNodeExplorer, BeamWalletCli, BeamNode, BeamBroadcaster

notifications:
  - provider: Email
    to:
      - big.romanov@gmail.com
